from typing import Any, Tuple, TypeVar, Type

_T = TypeVar('_T', bound=Colour)

class Colour:
    def __init__(self, value: int) -> None: ...

    def __eq__(self, other: Any) -> bool: ...

    def __ne__(self, other: Any) -> bool: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __hash__(self) -> int: ...

    @property
    def r(self) -> int: ...

    @property
    def g(self) -> int: ...

    @property
    def b(self) -> int: ...

    def to_rgb(self) -> Tuple[int, int, int]: ...

    @classmethod
    def from_rgb(cls: Type[_T], r: int, g: int, b: int) -> _T: ...

    @classmethod
    def default(cls: Type[_T]) -> _T: ...

    @classmethod
    def teal(cls: Type[_T]) -> _T: ...

    @classmethod
    def dark_teal(cls: Type[_T]) -> _T: ...

    @classmethod
    def green(cls: Type[_T]) -> _T: ...

    @classmethod
    def dark_green(cls: Type[_T]) -> _T: ...

    @classmethod
    def blue(cls: Type[_T]) -> _T: ...

    @classmethod
    def dark_blue(cls: Type[_T]) -> _T: ...

    @classmethod
    def purple(cls: Type[_T]) -> _T: ...

    @classmethod
    def dark_purple(cls: Type[_T]) -> _T: ...

    @classmethod
    def magenta(cls: Type[_T]) -> _T: ...

    @classmethod
    def dark_magenta(cls: Type[_T]) -> _T: ...

    @classmethod
    def gold(cls: Type[_T]) -> _T: ...

    @classmethod
    def dark_gold(cls: Type[_T]) -> _T: ...

    @classmethod
    def orange(cls: Type[_T]) -> _T: ...

    @classmethod
    def dark_orange(cls: Type[_T]) -> _T: ...

    @classmethod
    def red(cls: Type[_T]) -> _T: ...

    @classmethod
    def dark_red(cls: Type[_T]) -> _T: ...

    @classmethod
    def lighter_grey(cls: Type[_T]) -> _T: ...

    @classmethod
    def dark_grey(cls: Type[_T]) -> _T: ...

    @classmethod
    def light_grey(cls: Type[_T]) -> _T: ...

    @classmethod
    def darker_grey(cls: Type[_T]) -> _T: ...

    @classmethod
    def blurple(cls: Type[_T]) -> _T: ...

    @classmethod
    def greyple(cls: Type[_T]) -> _T: ...

Color = Colour
