import datetime

from .colour import Colour
from .types import RawEmbedDict, EmbedFooterData, EmbedImageData, EmbedVideoData, EmbedProviderData, EmbedAuthorData, EmbedFieldData

from typing import Any, Union, Dict, List, ClassVar, TypeVar, Type
from mypy_extensions import TypedDict

class _EmptyEmbed:
    def __bool__(self) -> bool: ...

    def __repr__(self) -> str: ...

EmptyEmbed: _EmptyEmbed = ...

class EmbedProxy:
    def __init__(self, layer: Dict[str, Any]) -> None: ...

    def __len__(self) -> int: ...

    def __repr__(self) -> str: ...

    def __getattr__(self, attr: str) -> _EmptyEmbed: ...

_T = TypeVar('_T', bound=Embed)

class Embed:
    title: str
    type: str
    description: str
    url: str
    colour: Union[int, Colour, _EmptyEmbed]
    color: Union[int, Colour, _EmptyEmbed]
    timestamp: Union[datetime.datetime, _EmptyEmbed]

    Empty: ClassVar[_EmptyEmbed]

    def __init__(self, *, color: Union[int, Colour, _EmptyEmbed] = ..., colour: Union[int, Colour, _EmptyEmbed] = ...,
                 title: str = ..., type: str = ..., url: str = ..., description: str = ...,
                 timestamp: datetime.datetime = ...) -> None: ...

    @classmethod
    def from_data(cls: Type[_T], data: RawEmbedDict) -> _T: ...

    @property
    def footer(self) -> EmbedFooterData: ...

    def set_footer(self, *, text: str = ..., icon_url: str = ...) -> _T: ...

    @property
    def image(self) -> EmbedImageData: ...

    def set_image(self, *, url: str) -> _T: ...

    @property
    def thumbnail(self) -> EmbedImageData: ...

    def set_thumbnail(self, *, url: str) -> _T: ...

    @property
    def video(self) -> EmbedVideoData: ...

    @property
    def provider(self) -> EmbedProviderData: ...

    @property
    def author(self) -> EmbedAuthorData: ...

    def set_author(self, *, name: str, url: str = ..., icon_url: str = ...) -> _T: ...

    @property
    def fields(self) -> List[EmbedFieldData]: ...

    def add_field(self, *, name: str, value: str, inline: bool = ...) -> _T: ...

    def clear_fields(self) -> None: ...

    def remove_field(self, index: int) -> None: ...

    def set_field_at(self, index: int, *, name: str, value: str, inline: bool = ...) -> _T: ...

    def to_dict(self) -> RawEmbedDict: ...
